"""
Unified Pydantic Model for TeacherResourceChapter
Auto-generated by combining 5 template(s)

Source files:
  - igcse_biology_4ed_tr_chapter_10.pdf
  - igcse_biology_4ed_tr_chapter_12.pdf
  - igcse_biology_4ed_tr_chapter_18.pdf
  - igcse_biology_4ed_tr_chapter_2.pdf
  - igcse_biology_4ed_tr_chapter_7.pdf

Generated: 2026-02-15T21:19:00.274783
"""

from typing import Optional, List, Any
from pydantic import BaseModel, Field, ConfigDict


# Docling-graph edge helper
def edge(label: str, **kwargs: Any) -> Any:
    """Helper to create graph edges with proper docling-graph metadata."""
    if "default" in kwargs or "default_factory" in kwargs:
        return Field(json_schema_extra={"edge_label": label}, **kwargs)
    return Field(default_factory=list, json_schema_extra={"edge_label": label}, **kwargs)


# Component classes (is_entity=False)

class LearningObjective(BaseModel):
    """Specific learning objectives or syllabus content for this topic"""
    model_config = ConfigDict(is_entity=False)

    level: str = Field(description="Difficulty level or tier of the objective", examples=["Core"])
    objective_text: str = Field(description="The actual learning objective statement", examples=["Describe a pathogen as a disease-causing organism"])


class LearningPlan(BaseModel):
    """Structured learning plan mapping syllabus objectives to learning intentions and success criteria"""
    model_config = ConfigDict(is_entity=False)

    syllabus_objectives: Optional[List[str]] = Field(default=None, description="Official syllabus learning objectives")
    learning_intentions: Optional[List[str]] = Field(default=None, description="What learners will explore or learn in this topic")
    success_criteria: Optional[List[str]] = Field(default=None, description="How learners will demonstrate their learning")


# Entity classes (is_entity=True, graph_id_fields=[...])

class CommonMisconception(BaseModel):
    """Common student misconceptions and strategies to address them"""
    model_config = ConfigDict(is_entity=True, graph_id_fields=['misconception'])

    misconception: str = Field(description="Description of the misconception", examples=["Learners can refer to pathogens as 'germs' or 'bugs'"])
    how_to_identify: str = Field(description="Method to identify if students hold this misconception", examples=["Ask learners to list all the words they can for the 'agents' that cause disease"])
    how_to_overcome: str = Field(description="Strategy to address and correct the misconception", examples=["Rank order the words that learners provide in terms of scientific appropriateness"])


class StarterActivity(BaseModel):
    """
    Activities to begin the lesson or topic.
    
    EXTRACTION RULE: Only extract activities that appear AFTER the '## Starter ideas' header.
    Activities under 'Main teaching ideas', 'Plenary ideas', or 'Homework ideas' do NOT belong here.
    """
    model_config = ConfigDict(is_entity=True, graph_id_fields=['activity_name'])

    activity_name: str = Field(description="Name or title of the activity (found after '## Starter ideas' header)", examples=["Disease and immunity - an initial assessment"])
    duration_minutes: int = Field(description="Duration of the activity in minutes", examples=[10])
    description: Optional[str] = Field(default=None, description="Detailed description of the activity", examples=["Students complete a diagnostic assessment"])


class MainTeachingActivity(BaseModel):
    """
    Core teaching activities for the topic.
    
    EXTRACTION RULE: Only extract activities that appear AFTER the '## Main teaching ideas' header.
    Activities under 'Starter ideas', 'Plenary ideas', or 'Homework ideas' do NOT belong here.
    """
    model_config = ConfigDict(is_entity=True, graph_id_fields=['activity_name'])

    activity_name: str = Field(description="Name or title of the activity (found after '## Main teaching ideas' header)", examples=["Finding patient zero"])
    duration_minutes: int = Field(description="Duration of the activity in minutes", examples=[50])
    description: Optional[str] = Field(default=None, description="Detailed description of the activity", examples=["Students investigate disease transmission patterns"])
    differentiation_ideas: Optional[str] = Field(default=None, description="Strategies for differentiating the activity for different learner needs", examples=["Provide scaffolding worksheets for struggling learners"])


class PlenaryActivity(BaseModel):
    """
    Activities to conclude the lesson or topic.
    
    EXTRACTION RULE: Only extract activities that appear AFTER the '## Plenary ideas' header.
    Activities under 'Starter ideas', 'Main teaching ideas', or 'Homework ideas' do NOT belong here.
    """
    model_config = ConfigDict(is_entity=True, graph_id_fields=['activity_name'])

    activity_name: str = Field(description="Name or title of the activity (found after '## Plenary ideas' header)", examples=["Brainstorming to structure an answer"])
    duration_minutes: int = Field(description="Duration of the activity in minutes", examples=[10])
    description: Optional[str] = Field(default=None, description="Detailed description of the activity", examples=["Students practice structuring exam answers"])


class HomeworkActivity(BaseModel):
    """
    Homework assignments or independent study tasks.
    
    EXTRACTION RULE: Only extract activities that appear AFTER the '## Homework ideas' header.
    Activities under 'Starter ideas', 'Main teaching ideas', or 'Plenary ideas' do NOT belong here.
    """
    model_config = ConfigDict(is_entity=True, graph_id_fields=['activity_name'])

    activity_name: str = Field(description="Name or title of the homework (found after '## Homework ideas' header)", examples=["Workbook Exercises 10.1-10.3"])
    description: Optional[str] = Field(default=None, description="Detailed description of the homework task", examples=["Complete exercises on pathogen transmission"])


class Activity(BaseModel):
    """
    Generic activity container - USE SPECIFIC ACTIVITY TYPES INSTEAD.
    
    IMPORTANT: Prefer using the specific activity types (StarterActivity, MainTeachingActivity, 
    PlenaryActivity, HomeworkActivity) based on the section header in the document:
    - '## Starter ideas' → StarterActivity
    - '## Main teaching ideas' → MainTeachingActivity  
    - '## Plenary ideas' → PlenaryActivity
    - '## Homework ideas' → HomeworkActivity
    """
    model_config = ConfigDict(is_entity=True, graph_id_fields=['activity_name'])

    activity_name: str = Field(description="Name or title of the activity", examples=["What is a cell?"])
    duration_minutes: int = Field(description="Estimated time to complete the activity in minutes", examples=[10])
    activity_type: str = Field(description="Category of activity based on section header: 'starter' (from Starter ideas), 'main' (from Main teaching ideas), 'plenary' (from Plenary ideas), 'homework' (from Homework ideas)", examples=["starter"])
    description: Optional[str] = Field(default=None, description="Detailed instructions for implementing the activity", examples=["Challenge learners to rank order objects by size"])
    resources_needed: Optional[List[str]] = Field(default=None, description="Materials or resources required for the activity")
    differentiation_ideas: Optional[str] = Field(default=None, description="Suggestions for adapting the activity for different learner needs", examples=["Provide sentence starters for support learners"])


class Resource(BaseModel):
    """All educational resources referenced in the chapter"""
    model_config = ConfigDict(is_entity=True, graph_id_fields=['resource_name'])

    resource_type: str = Field(description="Type of resource (Coursebook, Workbook, Practical Workbook, etc.)", examples=["Coursebook"])
    resource_name: str = Field(description="Specific name or identifier of the resource", examples=["Exercise 2.1: Animals, plants and bacteria"])


class Project(BaseModel):
    """Extended project work or investigations"""
    model_config = ConfigDict(is_entity=True, graph_id_fields=['project_title'])

    project_title: str = Field(description="Title of the project", examples=["Finding a vaccine for malaria"])
    guidance: Optional[str] = Field(default=None, description="Guidance or instructions for the project", examples=["Students research current vaccine development efforts"])


class Topic(BaseModel):
    """
    Sub-topics or sections within the chapter.
    
    ACTIVITY EXTRACTION RULES - Use document headers to categorize activities:
    Each topic section in the document has activities organized under specific headers.
    Extract activities to the correct list based on which header they appear after:
    
    Document Header                → Field to populate
    ─────────────────────────────────────────────────────
    '## Starter ideas'             → starter_activities
    '## Main teaching ideas'       → main_teaching_activities
    '## Plenary ideas'             → plenary_activities
    '## Homework ideas'            → homework_activities
    
    CRITICAL: An activity appearing after 'Plenary ideas' must go to plenary_activities,
    NOT to starter_activities or main_teaching_activities.
    """
    model_config = ConfigDict(is_entity=True, graph_id_fields=['topic_code'])

    topic_code: str = Field(description="Unique identifier for the topic", examples=["10.1A"])
    topic_title: str = Field(description="Title of the topic", examples=["Disease"])
    learning_hours: float = Field(description="Approximate number of teaching hours allocated to this topic", examples=[2])
    learning_objectives: List[LearningObjective] = edge(
        label="HAS_OBJECTIVE",
        default_factory=list,
        description="Specific learning objectives or syllabus content for this topic"
    )
    learning_intentions: Optional[str] = Field(
        default=None,
        description="What learners will explore or focus on in this topic",
        examples=["explore the causes of disease and the body's defence against pathogens"]
    )
    success_criteria: Optional[str] = Field(
        default=None,
        description="What learners should be able to do to demonstrate success",
        examples=["Learners will be able to describe the causes of disease and the body's defence against pathogens"]
    )
    resources: Optional[List[str]] = Field(
        default=None,
        description="Teaching resources referenced for this topic",
        examples=[['Coursebook: Getting started feature', 'Workbook: Exercises 10.1-3']]
    )
    common_misconceptions: Optional[List[CommonMisconception]] = edge(
        label="HAS_MISCONCEPTION",
        default_factory=list,
        description="Common student misconceptions and strategies to address them"
    )
    starter_activities: Optional[List[StarterActivity]] = edge(
        label="HAS_STARTER_ACTIVITY",
        default_factory=list,
        description="Activities listed after '## Starter ideas' header ONLY. Do NOT include Main/Plenary/Homework activities here."
    )
    main_teaching_activities: Optional[List[MainTeachingActivity]] = edge(
        label="HAS_MAIN_ACTIVITY",
        default_factory=list,
        description="Activities listed after '## Main teaching ideas' header ONLY. Do NOT include Starter/Plenary/Homework activities here."
    )
    plenary_activities: Optional[List[PlenaryActivity]] = edge(
        label="HAS_PLENARY_ACTIVITY",
        default_factory=list,
        description="Activities listed after '## Plenary ideas' header ONLY. Do NOT include Starter/Main/Homework activities here."
    )
    homework_activities: Optional[List[HomeworkActivity]] = edge(
        label="HAS_HOMEWORK_ACTIVITY",
        default_factory=list,
        description="Activities listed after '## Homework ideas' header ONLY. Do NOT include Starter/Main/Plenary activities here."
    )


# Root document class (MUST be last)

class TeacherResourceChapter(BaseModel):
    """Root document model for TeacherResourceChapter."""
    model_config = ConfigDict(is_entity=True, graph_id_fields=['chapter_number'])

    chapter_number: str = Field(description="The chapter identifier or number", examples=["10"])
    chapter_title: str = Field(description="The title or main topic of the chapter", examples=["Diseases and immunity"])
    subject: str = Field(description="The academic subject area", examples=["Biology"])
    curriculum: str = Field(description="The curriculum or qualification framework", examples=["CAMBRIDGE IGCSE™ BIOLOGY"])
    background_knowledge: Optional[str] = Field(
        default=None,
        description="Prior knowledge or context teachers should be aware of before teaching this chapter",
        examples=["Students should understand basic cell structure"]
    )
    teaching_skills_focus: Optional[str] = Field(
        default=None,
        description="Specific pedagogical skills or approaches emphasized in this chapter",
        examples=["Inquiry-based learning"]
    )
    language_support: Optional[str] = Field(
        default=None,
        description="Guidance for supporting language development and vocabulary acquisition",
        examples=["Key terminology: pathogen, antibody, immunity"]
    )
    topics: List[Topic] = edge(
        label="CONTAINS_TOPIC",
        default_factory=list,
        description="Sub-topics or sections within the chapter"
    )
    cross_curricular_links: Optional[List[str]] = Field(
        default=None,
        description="Connections to other subject areas or disciplines",
        examples=[['Mathematics: data analysis of disease spread', 'Geography: global health patterns']]
    )
    projects: Optional[List[Project]] = edge(
        label="HAS_PROJECT",
        default_factory=list,
        description="Extended project work or investigations"
    )
    digital_resources: Optional[List[str]] = Field(
        default=None,
        description="Links to digital or online resources",
        examples=[['Interactive simulation: immune response', 'Video: vaccination process']]
    )
    project_guidance: Optional[str] = Field(
        default=None,
        description="Guidance for extended projects or investigations related to the chapter",
        examples=["Using photography to record plant responses"]
    )
    panel_insights: Optional[str] = Field(
        default=None,
        description="Insights or recommendations from curriculum experts or teacher panels",
        examples=["Cambridge panel recommends using flipbooks for visual learners"]
    )
    learning_plan: Optional[LearningPlan] = Field(
        default=None,
        description="Structured learning plan mapping syllabus objectives to learning intentions and success criteria"
    )
    pedagogical_notes: Optional[List[str]] = Field(
        default=None,
        description="Additional teaching notes, tips, or panel comments from experienced educators"
    )
    activities: List[Activity] = edge(
        label="HAS_ACTIVITY",
        default_factory=list,
        description="All teaching activities across the chapter with detailed implementation guidance"
    )
    resources: Optional[List[Resource]] = edge(
        label="HAS_RESOURCE",
        default_factory=list,
        description="All educational resources referenced in the chapter"
    )
    curriculum_framework: str = Field(
        description="The educational framework or qualification this resource supports",
        examples=["CAMBRIDGE IGCSE™ BIOLOGY"]
    )